import tkinter as tk
window=tk.Tk()
window.geometry("250x370")
def onclick():
    print(1)
btn1=tk.Button(text="Зал", command=onclick)
btn1.grid(row=0, column=0)
chkvar1=tk.IntVar()
chkbtn1=tk.Checkbutton(text="выбор лампочки", variable=chkvar1, onvalue=1, offvalue=0)
chkbtn1.grid(row=1, column=0)
scl1=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl1.grid(row=2, column=0)
btn3=tk.Button(text="Ванная комната", command=onclick)
btn3.grid(row=6, column=0)
chkvar3=tk.IntVar()
chkbtn3=tk.Checkbutton(text="выбор лампочки", variable=chkvar3, onvalue=1, offvalue=0)
chkbtn3.grid(row=7, column=0)
scl3=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl3.grid(row=8, column=0)
btn4=tk.Button(text="Кухня", command=onclick)
btn4.grid(row=9, column=0)
chkvar4=tk.IntVar()
chkbtn4=tk.Checkbutton(text="выбор лампочки", variable=chkvar4, onvalue=1, offvalue=0)
chkbtn4.grid(row=10, column=0)
scl4=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl4.grid(row=11, column=0)
window.mainloop()
